// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzl_iwdtv9SAvv66TiHtIoYRnRwCLQIoM',
    appId: '1:124048731719:android:db1a42bfb521dbf85e4b62',
    messagingSenderId: '124048731719',
    projectId: 'commerce-app-20a02',
    storageBucket: 'commerce-app-20a02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP50h1Lvt3cVFISNN7wj3idwTxykWOoRw',
    appId: '1:124048731719:ios:2074bea6d5d8b1075e4b62',
    messagingSenderId: '124048731719',
    projectId: 'commerce-app-20a02',
    storageBucket: 'commerce-app-20a02.appspot.com',
    iosClientId: '124048731719-806v4gd43vno0btrf2u8nrm75krch2tj.apps.googleusercontent.com',
    iosBundleId: 'com.example.commerceApp',
  );
}
